### ISSUE TITLE
RAILS 7 Using ESBUILD 

### ISSUE THREAD

**Issue by muaaz-vf** [DavyJonesLocker/client_side_validations-simple_form#134]
Hey using ESBUILD plus bootstrap have included jquery using yarn as well and ran the command 
`yarn add @client-side-validations/simple-form`
plus included files in application.js under javascript folder at root.
`import jquery from "jquery";
import '@client-side-validations/simple-form/src/index.bootstrap4'
`
Plus it throws error,
```
19:34:57 web.1  | started with pid 108082
19:34:57 js.1   | started with pid 108083
19:34:57 css.1  | started with pid 108084
19:34:57 css.1  | yarn run v1.22.17
19:34:57 js.1   | yarn run v1.22.17
19:34:57 css.1  | $ sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules --watch
19:34:57 js.1   | $ node esbuild.config.js --watch
19:34:57 js.1   | ✘ [ERROR] Could not resolve "@client-side-validations/client-side-validations"
19:34:57 js.1   | 
19:34:57 js.1   |     ../../node_modules/@client-side-validations/simple-form/src/index.bootstrap4.js:2:34:
19:34:57 js.1   |       2 │ ...Validations from '@client-side-validations/client-side-validations'
19:34:57 js.1   |         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19:34:57 js.1   | 
19:34:57 js.1   |   You can mark the path "@client-side-validations/client-side-validations" as external to exclude it from the bundle, which will remove this error.
19:34:57 js.1   | 
19:34:57 js.1   | error Command failed with exit code 1.
19:34:57 js.1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:34:58 js.1   | exited with code 1
19:34:58 system | sending SIGTERM to all processes
19:34:58 web.1  | ["DEBUGGER Exception: /home/muaaz/.rvm/gems/ruby-3.0.3/gems/debug-1.4.0/lib/debug/thread_client.rb:986",
19:34:58 web.1  |  #<SignalException: SIGTERM>,
19:34:58 web.1  |  ["/home/muaaz/.rvm/gems/ruby-3.0.3/gems/debug-1.4.0/lib/debug/thread_client.rb:694:in `pop'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/debug-1.4.0/lib/debug/thread_client.rb:694:in `wait_next_action_'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/debug-1.4.0/lib/debug/thread_client.rb:676:in `wait_next_action'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/debug-1.4.0/lib/debug/thread_client.rb:201:in `wait_reply'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/debug-1.4.0/lib/debug/thread_client.rb:205:in `on_load'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/debug-1.4.0/lib/debug/session.rb:118:in `block in initialize'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/activerecord-7.0.0/lib/active_record/database_configurations.rb:4:in `<main>'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/activerecord-7.0.0/lib/active_record/base.rb:13:in `<main>'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/client_side_validations-20.0.2/lib/client_side_validations/active_record.rb:6:in `<main>'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/client_side_validations-20.0.2/lib/client_side_validations.rb:5:in `<main>'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:55:in `each'",
19:34:58 web.1  |   "/home/muaaz/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:55:in `block in require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:44:in `each'",
19:34:58 web.1  |   "/home/muaaz/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:44:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler.rb:175:in `require'",
19:34:58 web.1  |   "/home/muaaz/projects/seamless_capital/config/application.rb:7:in `<main>'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/railties-7.0.0/lib/rails/commands/server/server_command.rb:137:in `block in perform'",
19:34:58 web.1  |   "<internal:kernel>:90:in `tap'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/railties-7.0.0/lib/rails/commands/server/server_command.rb:134:in `perform'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/railties-7.0.0/lib/rails/command/base.rb:87:in `perform'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/railties-7.0.0/lib/rails/command.rb:48:in `invoke'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/railties-7.0.0/lib/rails/commands.rb:18:in `<main>'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
19:34:58 web.1  |   "/home/muaaz/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
19:34:58 web.1  |   "bin/rails:4:in `<main>'"]]
```
Any help will be apperciated.

**Comment by muaaz-vf** [comment]
Thank you, your quick response is much apperciated.

**Comment by tagliala** [comment]
Welcome!

PS: we met in ActiveAdmin / Rails 7 issue :)
